apiVersion: v1
kind: Service
metadata:
  name: calculator-crud-service
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 3030          # Port for the service
      targetPort: 3030    # Port on the container
      nodePort: 30030     # Port on your host machine (must be between 30000–32767)